name: build and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:


jobs:
           
  ubuntu-all-build:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut test
        uses: actions/checkout@v4  
          
      - name: cmake-configure
        uses: snickerbockers/cmake-configure@prerel1

      - name: Build sources and tests
        run: |
           cmake -S . -B build/release -D CMAKE_BUILD_TYPE=Release
           cmake --build build/release
           
      - name: Run tests
        run: |
          sudo chmod +x run-tests.sh
          ./run-tests.sh

  ubuntu-test:
    runs-on: ubuntu-latest
    needs: ubuntu-all-build
    steps:
    - name: Run tests
      run: |
        cmake -S . -B build/release -D CMAKE_BUILD_TYPE=Release
        cmake --build build/release
        chmod +x run-tests.sh
        ./run-tests.sh
           

    
    
           
