name: build and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  all-build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      
    runs-on: ${{ matrix.os }}
    steps:
      - name: CheckOut test
        uses: actions/checkout@v4
      
      - name: Set up compiler
        run: |
          sudo apt-get update
          sudo apt-get install g++
          
      - name: cmake-configure
        uses: snickerbockers/cmake-configure@prerel1

      - name: Build sources and tests
        run: |
           cmake -S . -B build/ -D CMAKE_BUILD_TYPE=Release
           cmake --build build/release

    
    
           
