name: build and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:


jobs:
  win-build:      
    runs-on: windows-latest
    steps:
      - name: CheckOut test
        uses: actions/checkout@v4  
          
      - name: cmake-configure
        uses: snickerbockers/cmake-configure@prerel1

      - name: Build sources and tests
        run: |
             cmake -S . -B build/release -G "MinGW Makefiles" -D CMAKE_BUILD_TYPE=Release
             cmake --build build/release
           
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut test
        uses: actions/checkout@v4  
          
      - name: cmake-configure
        uses: snickerbockers/cmake-configure@prerel1

      - name: Build sources and tests
        run: |
           cmake -S . -B build/release -D CMAKE_BUILD_TYPE=Release
           cmake --build build/release
           

  test-win:
    needs: win-build
      
    runs-on: windows-latest
    steps:
    - name: Run tests
      run: |
         cmake -S . -B build/release -G "MinGW Makefiles" -D CMAKE_BUILD_TYPE=Release
         cmake --build build/release
         ./run-tests.sh
      
  test-lin:
     needs: ubuntu-build
      
     runs-on: ubuntu-latest
     steps:
       - name: Run tests
         run: |
           cmake -S . -B build/release -D CMAKE_BUILD_TYPE=Release
           cmake --build build/release
           chmod +x run-tests.sh
           ./run-tests.sh


    
    
           
